[package]
name = "advent_of_code2023"
version = "0.1.0"
edition = "2021"

[lib]
name = "common"
path = "src/common.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
